# Generated by Django 5.0.7 on 2024-07-27 04:54

import django.core.validators
import django.db.models.deletion
import referrals.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("useraccounts", "0003_alter_customuser_options_customuser_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("description", models.TextField()),
                (
                    "product_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="product_images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg", "tiff"]
                            ),
                            referrals.validators.validate_file_size,
                        ],
                    ),
                ),
                (
                    "product_value",
                    models.CharField(
                        choices=[
                            ("whatsapp", "Whatsapp"),
                            ("phone", "Phone"),
                            ("website", "Website"),
                        ],
                        default="website",
                        max_length=10,
                    ),
                ),
                ("product_link", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "shares",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MaxValueValidator(1000000000)
                        ],
                    ),
                ),
                (
                    "traffic",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MaxValueValidator(1000000000)
                        ],
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="useraccounts.companyprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
    ]
