# Generated by Django 5.0.6 on 2024-07-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("individual", "Individual"), ("company", "Company")],
                default="individual",
                max_length=20,
            ),
        ),
    ]
