# Generated by Django 5.0.7 on 2024-07-27 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0002_supportticket"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supportticket",
            options={
                "verbose_name": "Support Ticket",
                "verbose_name_plural": "Support Tickets",
            },
        ),
    ]
