# Generated by Django 5.0.6 on 2024-07-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0002_customuser_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("individual", "Individual"),
                    ("company", "Company"),
                    ("admin", "Admin"),
                ],
                max_length=20,
            ),
        ),
    ]
