# Generated by Django 5.0.7 on 2024-07-27 06:28

import referrals.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0003_alter_supportticket_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        upload_to="ranking_icons/",
                        validators=[referrals.validators.validate_file_size],
                    ),
                ),
                ("user", models.CharField(max_length=255)),
                ("rank_level", models.IntegerField(default=0)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("gold pro", "Gold Pro"),
                            ("gold", "Gold"),
                            ("silver pro", "Silver Pro"),
                            ("silver", "Silver"),
                            ("platinum", "Platinum"),
                        ],
                        default="silver",
                        max_length=15,
                    ),
                ),
                ("total_recruits", models.IntegerField(default=0)),
                ("bonus", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("enabled", "Enabled"), ("disabled", "Disabled")],
                        default="enabled",
                        max_length=10,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "User Ranking",
                "verbose_name_plural": "User Rankings",
            },
        ),
    ]
