# Generated by Django 5.0.7 on 2024-07-27 15:06

import referrals.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0004_userranking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userranking",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="ranking_icons/",
                validators=[referrals.validators.validate_file_size],
            ),
        ),
        migrations.AlterField(
            model_name="userranking",
            name="user",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
