# Generated by Django 5.0.6 on 2024-07-24 11:16

import django.core.validators
import referrals.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0004_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(
                upload_to="product_images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg", "tiff"]
                    ),
                    referrals.validators.validate_file_size,
                ],
            ),
        ),
    ]
