# Generated by Django 5.0.7 on 2024-08-01 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0004_staff"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staff",
            options={"verbose_name": "Staff", "verbose_name_plural": "Staff"},
        ),
    ]
