# Generated by Django 5.0.6 on 2024-07-24 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0006_supportticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="submitted_by",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="support_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
