# Generated by Django 5.0.6 on 2024-07-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0007_supportticket_submitted_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supportticket",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="supportticket",
            name="object_id",
        ),
    ]
