# Generated by Django 5.0.6 on 2024-07-24 15:15

import django.db.models.deletion
import referrals.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0008_remove_supportticket_content_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        upload_to="ranking_icons/",
                        validators=[referrals.validators.validate_file_size],
                    ),
                ),
                ("rank_level", models.IntegerField(default=0)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("gold pro", "Gold Pro"),
                            ("gold", "Gold"),
                            ("silver pro", "Silver Pro"),
                            ("silver", "Silver"),
                            ("platinum", "Platinum"),
                        ],
                        default="silver",
                        max_length=15,
                    ),
                ),
                ("total_recruits", models.IntegerField(default=0)),
                ("bonus", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("enabled", "Enabled"), ("disabled", "Disabled")],
                        default="enabled",
                        max_length=10,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
