# Generated by Django 5.0.6 on 2024-07-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0009_userranking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userranking",
            name="user",
            field=models.CharField(max_length=255),
        ),
    ]
