# Generated by Django 5.0.6 on 2024-07-25 12:26

import django.core.validators
import referrals.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0010_alter_userranking_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportticket",
            name="attachments",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="support_ticket_attachments/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg", "tiff", "pdf"]
                    ),
                    referrals.validators.validate_file_size,
                ],
            ),
        ),
    ]
