# Generated by Django 5.0.6 on 2024-07-26 10:18

import django.core.validators
import referrals.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0011_alter_supportticket_attachments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="product_images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg", "tiff"]
                    ),
                    referrals.validators.validate_file_size,
                ],
            ),
        ),
    ]
