# Generated by Django 5.0.6 on 2024-07-26 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0013_userregistration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userregistration",
            old_name="action",
            new_name="status",
        ),
    ]
