# Generated by Django 5.0.6 on 2024-07-26 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0014_rename_action_userregistration_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("pending", "Pending"),
                            ("decline", "Decline"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company_name",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_registration",
                        to="referrals.company",
                    ),
                ),
                (
                    "registration_no",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_number",
                        to="referrals.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Registration",
                "verbose_name_plural": "Business Registrations",
            },
        ),
    ]
