# Generated by Django 5.0.6 on 2024-07-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0015_businessregistration"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_value",
            field=models.CharField(
                choices=[
                    ("whatsapp", "Whatsapp"),
                    ("phone", "Phone"),
                    ("website", "Website"),
                ],
                default="website",
                max_length=10,
            ),
        ),
    ]
