# Generated by Django 5.0.7 on 2024-07-27 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("useraccounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companyprofile",
            options={
                "verbose_name": "Company Profile",
                "verbose_name_plural": "Company Profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelOptions(
            name="individualprofile",
            options={
                "verbose_name": "Individual Profile",
                "verbose_name_plural": "Individual Profiles",
            },
        ),
        migrations.AlterUniqueTogether(
            name="individualprofile",
            unique_together={("first_name", "last_name")},
        ),
    ]
